name: GitHub Profile Views Counter CI
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{81fbdbb7c3cf465eb5ad6fa5ae2dc764}}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      - uses: ${{81fbdbb7c3cf465eb5ad6fa5ae2dc764}}
